# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - scratch/**
    - test_*.dart
    - query_tables.dart
    - setup_users.dart

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: true
